name: Test

on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.python-version }} ${{ matrix.os }} ${{ matrix.debug == 1 && 'debug' || ' ' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.14', '3.14t']
        debug: [0]
        include:
          - os: ubuntu-latest
            python-version: '3.14t'
            debug: 1

    steps:
    - uses: actions/checkout@v5
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup env
      shell: bash
      run: |
        if test ${{ matrix.debug }} == 1; then
          echo "CFLAGS=-UNDEBUG" >> $GITHUB_ENV
        fi
    - name: test
      shell: bash
      run: |
        python3 -m pip install setuptools pytest
        python3 setup.py build_ext --inplace
        PYTHONPATH=src python3 -m pytest
